### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by ghost** [astarasikov/HuffmanArchiver#1]
Hello. Could you tell me how I can build this, please? What version of Visual Studio did you use? How to find the versions of the libs you used? Thank you.

**Comment by astarasikov** [comment]
I used monodevelop. I also built it with visual studio 2008 for Windows.
You will need GTK+ library binaries for Windows, though.

I have just checked and it builds I'm monodevelop just fine, if you go to
project settings and select .net runtime and set the C# language to version
3.0

P.S. I think there is also a DVD with binaries at HSE :)

**Comment by ghost** [comment]
Thank you ;D
